# Complements

## Schur-Zassenhaus

This section is devoted to the proof of the following powerful theorem:

THEOREM[schur-zassenhaus] Schur-Zassenhaus
> Let $G$ be finite and $N \lhd_b G$ of order $a$.
>
> 1. If $(a,b) = 1$, then there exists a complementary subgroup of order $b$.
> 2. If, moreover, $N$ or $G/N$ is soluble, then all such subgroups are conjugated.

In fact, it was proven in 1963 by Feit and Thompson that all finite groups
of odd order are soluble, which means that the solubility assumption in (2)
is actually superfluous.
However, the proof is 254 pages long and we don't want to rely on it in this
short summary.

### Abelian case

### General case

## Hall theory
